apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedemoapp-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: kubedemoapp
  template:
    metadata:
      labels:
        app: kubedemoapp
    spec:
      containers:
        - name: kubedemoapp
          image: teju898/week8:t1 # use your Docker Hub image
          ports:
            - containerPort: 5000

